version: '3.8'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ".:/app"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: